repos:
  - repo: local
    hooks:
    - id: generate-categories-and-tags
      name: Generate categories and tags
      description: Generate categories and tags defined in posts and wikis
      entry: node ./script/generate_categories_tags_data.js
      language: node
      stages: ["commit", "push"]

